stages:
  - test

maven:
  image: maven:3.8.6-openjdk-11
  stage: test
  services:
    - name: selenium/standalone-chrome:latest
      alias: selenium
  script:
    - mvn test
  artifacts:
    paths:
      - target/surefire-reports/ # Ensure this path matches where your test results are saved
  cache:
    paths:
      - .m2/repository # Caches Maven dependencies to speed up the build
