image: maven:3.8.5-openjdk-17

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.test.failure.ignore=true"

# cache:
#   paths:
#     - .m2/repository

test_job:
  stage: test
  script:
    - mvn test
