image: maven:3.8.7-jdk-17

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.test.failure.ignore=true"

cache:
  paths:
    - .m2/repository

test_job:
  stage: test
  script:
    - mvn clean test
  artifacts:
    paths:
      - target/surefire-reports/*.xml
    reports:
      junit: target/surefire-reports/*.xml
    expire_in: 1 week
